name: Clang nightly build

on:
  workflow_dispatch:

jobs:
  build-using-clang:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:
      - name: Check out repo
        uses: actions/checkout@v2.3.4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: foxy

      - name: Store all package names to ENV
        run: |
          mkdir src
          vcs import --recursive src/ < build_depends.repos
          mkdir vendor_ws
          vcs import --recursive vendor_ws/ < src/autoware/AutowareArchitectureProposal.iv/build_depends.repos
          echo "PACKAGE_NAMES=$(colcon list -nt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Install OpenMP lib for Clang
        run: |
          sudo apt install -y libomp-dev

      - name: Run action-ros-ci
        id: action_ros_ci_step
        uses: ros-tooling/action-ros-ci@0.1.2
        with:
          package-name: ${{ env.PACKAGE_NAMES }}
          target-ros2-distro: foxy
          vcs-repo-file-url: build_depends.repos
          #colcon-mixin-name: clang-libcxx
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
          extra-cmake-args: -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
